version: '3.9'

services:
  mongo:
    image: mongo:5.0.7
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=ropuszka
  
  mongo-express:
    image: mongo-express:1.0.0-alpha
    depends_on:
      - "mongo"
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongo

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/db-data:/var/lib/postgresql/data
      - ./postgres/init/00_init_db.sql:/docker-entrypoint-initdb.d/00_init_db.sql
      - ./postgres/init/01_insert_shop.sql/:/docker-entrypoint-initdb.d/01_insert_shop.sql
      - ./postgres/init/02_insert_product.sql/:/docker-entrypoint-initdb.d/02_insert_product.sql
      - ./postgres/init/03_insert_client.sql/:/docker-entrypoint-initdb.d/03_insert_client.sql
      - ./postgres/init/04_insert_discount.sql/:/docker-entrypoint-initdb.d/04_insert_discount.sql
      - ./postgres/init/05_insert_product_discount.sql/:/docker-entrypoint-initdb.d/05_insert_product_discount.sql
      - ./postgres/init/06_insert_purchase.sql/:/docker-entrypoint-initdb.d/06_insert_purchase.sql
      - ./postgres/init/07_insert_product_purchase.sql/:/docker-entrypoint-initdb.d/07_insert_product_purchase.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ropuszka
  
  pgadmin4:
    image: dpage/pgadmin4:6
    depends_on:
      - "postgres"
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@ropuszka.io
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - ./postgres/servers.json:/pgadmin4/servers.json
