
CREATE SCHEMA IF NOT EXISTS ropuszka;

-- ************************* SqlDBM: PostgreSQL *************************
-- ****** Generated by SqlDBM: BGD_project, v3 by mprx345@gmail.com *****



-- ************************************** Client

CREATE TABLE ropuszka.client
(
    "id"          bigint NOT NULL,
    name          text NOT NULL,
    date_of_birth date NOT NULL,
    email_address text NOT NULL,
    CONSTRAINT PK_23 PRIMARY KEY ( "id" )
);


-- ************************************** Discount

CREATE TABLE ropuszka.discount
(
    "id"       bigint NOT NULL,
    name       text NOT NULL,
    percentage decimal(18,3) NOT NULL,
    date_from  date NOT NULL,
    date_to    date NOT NULL,
    CONSTRAINT PK_67 PRIMARY KEY ( "id" )
);


-- ************************************** Product

CREATE TABLE ropuszka.product
(
    "id"          bigint NOT NULL,
    name          text NOT NULL,
    price         decimal(18,2) NOT NULL,
    producer_name text NOT NULL,
    id_discount   bigint NOT NULL,
    CONSTRAINT PK_29 PRIMARY KEY ( "id" ),
    CONSTRAINT FK_70 FOREIGN KEY ( id_discount ) REFERENCES ropuszka.discount ( "id" )
);

CREATE INDEX FK_72 ON ropuszka.product
    (
     id_discount
        );


-- ************************************** Shop

CREATE TABLE ropuszka.shop
(
    "id"          bigint NOT NULL,
    address       text NOT NULL,
    phone_number  text NOT NULL,
    email_address text NOT NULL,
    CONSTRAINT PK_10 PRIMARY KEY ( "id" )
);



-- ************************************** Purchase

CREATE TABLE ropuszka.purchase
(
    "id"      bigint NOT NULL,
    "date"    timestamp NOT NULL,
    id_shop   bigint NOT NULL,
    id_client bigint NOT NULL,
    CONSTRAINT PK_18 PRIMARY KEY ( "id" ),
    CONSTRAINT FK_48 FOREIGN KEY ( id_client ) REFERENCES ropuszka.client ( "id" ),
    CONSTRAINT FK_51 FOREIGN KEY ( id_shop ) REFERENCES ropuszka.shop ( "id" )
);

CREATE INDEX FK_50 ON ropuszka.purchase
    (
     id_client
        );

CREATE INDEX FK_53 ON ropuszka.purchase
    (
     id_shop
        );


-- ************************************** ProductPurchase

CREATE TABLE ropuszka.product_purchase
(
    "id"        bigint NOT NULL,
    id_product  bigint NOT NULL,
    id_purchase bigint NOT NULL,
    quantity    decimal(18,2) NOT NULL,
    CONSTRAINT PK_57 PRIMARY KEY ( "id" ),
    CONSTRAINT FK_58 FOREIGN KEY ( id_product ) REFERENCES ropuszka.product ( "id" ),
    CONSTRAINT FK_61 FOREIGN KEY ( id_purchase ) REFERENCES ropuszka.purchase ( "id" )
);

CREATE INDEX FK_60 ON ropuszka.product_purchase
    (
     id_product
        );

CREATE INDEX FK_63 ON ropuszka.product_purchase
    (
     id_purchase
        );
