
CREATE SCHEMA IF NOT EXISTS ropuszka;

-- ************************* SqlDBM: PostgreSQL *************************
-- ****** Generated by SqlDBM: BGD_project, v3 by mprx345@gmail.com *****



-- ************************************** Client

CREATE TABLE client
(
    "id"          bigint NOT NULL,
    name          text NOT NULL,
    date_of_birth date NOT NULL,
    email_address text NOT NULL,
    CONSTRAINT PK_23 PRIMARY KEY ( "id" )
);


-- ************************************** Product

CREATE TABLE product
(
    "id"          bigint NOT NULL,
    name          text NOT NULL,
    price         decimal(18,2) NOT NULL,
    producer_name text NOT NULL,
    CONSTRAINT PK_29 PRIMARY KEY ( "id" )
);


-- ************************************** Shop

CREATE TABLE shop
(
    "id"          bigint NOT NULL,
    address       text NOT NULL,
    phone_number  text NOT NULL,
    email_address text NOT NULL,
    CONSTRAINT PK_10 PRIMARY KEY ( "id" )
);



-- ************************************** Purchase

CREATE TABLE purchase
(
    "id"      bigint NOT NULL,
    "date"    timestamp NOT NULL,
    id_shop   bigint NOT NULL,
    id_client bigint NOT NULL,
    CONSTRAINT PK_18 PRIMARY KEY ( "id" ),
    CONSTRAINT FK_48 FOREIGN KEY ( id_client ) REFERENCES client ( "id" ),
    CONSTRAINT FK_51 FOREIGN KEY ( id_shop ) REFERENCES shop ( "id" )
);

CREATE INDEX FK_50 ON purchase
    (
     id_client
        );

CREATE INDEX FK_53 ON purchase
    (
     id_shop
        );


-- ************************************** ProductPurchase

CREATE TABLE product_purchase
(
    "id"        bigint NOT NULL,
    id_product  bigint NOT NULL,
    id_purchase bigint NOT NULL,
    quantity    decimal(18,2) NOT NULL,
    CONSTRAINT PK_57 PRIMARY KEY ( "id" ),
    CONSTRAINT FK_58 FOREIGN KEY ( id_product ) REFERENCES product ( "id" ),
    CONSTRAINT FK_61 FOREIGN KEY ( id_purchase ) REFERENCES purchase ( "id" )
);

CREATE INDEX FK_60 ON product_purchase
    (
     id_product
        );

CREATE INDEX FK_63 ON product_purchase
    (
     id_purchase
        );
